use_default_settings: true

general:
  instance_name: wine-cellar-search

search:
  formats:
    - html
    - json

server:
  secret_key: change-me
  limiter: false
  image_proxy: false
  public_instance: false

ui:
  static_use_hash: true
